/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dataEvmContractsGetContractMetadata } from "../../funcs/dataEvmContractsGetContractMetadata.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetContractMetadataRequest$inboundSchema,
};

export const tool$dataEvmContractsGetContractMetadata: ToolDefinition<
  typeof args
> = {
  name: "data-evm-contracts_get-contract-metadata",
  description: `Get contract metadata

Gets metadata about the contract at the given address.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await dataEvmContractsGetContractMetadata(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
