/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dataEvmTransactionsListErc1155Transactions } from "../../funcs/dataEvmTransactionsListErc1155Transactions.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListErc1155TransactionsRequest$inboundSchema,
};

export const tool$dataEvmTransactionsListErc1155Transactions: ToolDefinition<
  typeof args
> = {
  name: "data-evm-transactions_list-erc1155-transactions",
  description: `List ERC-1155 transfers

Lists ERC-1155 transfers for an address. Filterable by block range.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await dataEvmTransactionsListErc1155Transactions(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
