/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dataOperationsGetOperationResult } from "../../funcs/dataOperationsGetOperationResult.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetOperationResultRequest$inboundSchema,
};

export const tool$dataOperationsGetOperationResult: ToolDefinition<
  typeof args
> = {
  name: "data-operations_get-operation-result",
  description: `Get operation

Gets operation details for the given operation id.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await dataOperationsGetOperationResult(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
