/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dataIcmGet } from "../../funcs/dataIcmGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetIcmMessageRequest$inboundSchema,
};

export const tool$dataIcmGet: ToolDefinition<typeof args> = {
  name: "data-icm-get",
  description: `Get an ICM message

Gets an ICM message by teleporter message ID.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await dataIcmGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
