/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dataWebhooksAddAddressesToWebhook } from "../../funcs/dataWebhooksAddAddressesToWebhook.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.AddAddressesToWebhookRequest$inboundSchema,
};

export const tool$dataWebhooksAddAddressesToWebhook: ToolDefinition<
  typeof args
> = {
  name: "data-webhooks_add-addresses-to-webhook",
  description: `Add addresses to webhook

Add addresses to webhook.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await dataWebhooksAddAddressesToWebhook(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
