/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dataEvmBalancesGetNativeBalance } from "../../funcs/dataEvmBalancesGetNativeBalance.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetNativeBalanceRequest$inboundSchema,
};

export const tool$dataEvmBalancesGetNativeBalance: ToolDefinition<typeof args> =
  {
    name: "data-evm-balances_get-native-balance",
    description: `Get native token balance

Gets native token balance of a wallet address.

Balance at a given block can be retrieved with the \`blockNumber\` parameter.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await dataEvmBalancesGetNativeBalance(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
