/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dataTeleporterListTeleporterMessages } from "../../funcs/dataTeleporterListTeleporterMessages.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListTeleporterMessagesRequest$inboundSchema,
};

export const tool$dataTeleporterListTeleporterMessages: ToolDefinition<
  typeof args
> = {
  name: "data-teleporter-list-teleporter-messages",
  description:
    `**[Deprecated]** Lists teleporter messages. Ordered by timestamp in  descending order.

⚠️ **This operation will be removed in a future release.  Please use /v1/icm/messages endpoint instead** .`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await dataTeleporterListTeleporterMessages(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
