/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metricsChainsListNftHolders } from "../../funcs/metricsChainsListNftHolders.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetNftHoldersByContractAddressRequest$inboundSchema,
};

export const tool$metricsChainsListNftHolders: ToolDefinition<typeof args> = {
  name: "metrics-chains-list-nft-holders",
  description: `Get NFT holders by contract address

Get list of NFT holders and number of NFTs held by contract address.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metricsChainsListNftHolders(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
