/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metricsChainMetricsGetEvmChainRollingWindowMetrics } from "../../funcs/metricsChainMetricsGetEvmChainRollingWindowMetrics.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetEvmChainRollingWindowMetricsRequest$inboundSchema,
};

export const tool$metricsChainMetricsGetEvmChainRollingWindowMetrics:
  ToolDefinition<typeof args> = {
    name: "metrics-chain-metrics_get-evm-chain-rolling-window-metrics",
    description: `Get rolling window metrics for EVM chains

Gets the rolling window metrics for an EVM chain for the last hour, day, month, year, and all time.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await metricsChainMetricsGetEvmChainRollingWindowMetrics(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
