/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metricsChainsListBTCbBridgersAboveThreshold } from "../../funcs/metricsChainsListBTCbBridgersAboveThreshold.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAddressesByBtcbBridgedRequest$inboundSchema,
};

export const tool$metricsChainsListBTCbBridgersAboveThreshold: ToolDefinition<
  typeof args
> = {
  name: "metrics-chains-list-BT-cb-bridgers-above-threshold",
  description: `Get addresses by BTCb bridged balance

Get list of addresses and their net bridged amounts that have bridged more than a certain threshold.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metricsChainsListBTCbBridgersAboveThreshold(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
