/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metricsSubnetsGetValidators } from "../../funcs/metricsSubnetsGetValidators.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetValidatorsByDateRangeRequest$inboundSchema,
};

export const tool$metricsSubnetsGetValidators: ToolDefinition<typeof args> = {
  name: "metrics-subnets-get-validators",
  description: `Get addresses running validators during a given time frame

Get list of addresses and AddValidatorTx timestamps set to receive awards for validation periods during the specified time frame.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metricsSubnetsGetValidators(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
