/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksGenerateOrRotateSharedSecret } from "../../funcs/webhooksGenerateOrRotateSharedSecret.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$webhooksGenerateOrRotateSharedSecret: ToolDefinition = {
  name: "webhooks-generate-or-rotate-shared-secret",
  description: `Generate or rotate a shared secret

Generates a new shared secret or rotate an existing one.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await webhooksGenerateOrRotateSharedSecret(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
