/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { AvalancheSDKChains } from "./avalanchesdkchains.js";

export class AvalancheSDKEvm extends ClientSDK {
    private _chains?: AvalancheSDKChains;
    get chains(): AvalancheSDKChains {
        return (this._chains ??= new AvalancheSDKChains(this.options$));
    }
}
