/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { glacierEvmChainsGetChainInfo } from "../funcs/glacierEvmChainsGetChainInfo.js";
import { glacierEvmChainsSupportedChains } from "../funcs/glacierEvmChainsSupportedChains.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Chains extends ClientSDK {
    /**
     * List chains
     *
     * @remarks
     * Lists the supported EVM-compatible chains. Filterable by network.
     */
    async supportedChains(
        request: operations.SupportedChainsRequest,
        options?: RequestOptions
    ): Promise<components.ListChainsResponse> {
        return unwrapAsync(glacierEvmChainsSupportedChains(this, request, options));
    }

    /**
     * Get chain information
     *
     * @remarks
     * Gets chain information for the EVM-compatible chain if supported by the api.
     */
    async getChainInfo(
        request: operations.GetChainInfoRequest,
        options?: RequestOptions
    ): Promise<components.GetChainResponse> {
        return unwrapAsync(glacierEvmChainsGetChainInfo(this, request, options));
    }
}
