/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Chains } from "./chains.js";

export class Evm extends ClientSDK {
  private _chains?: Chains;
  get chains(): Chains {
    return (this._chains ??= new Chains(this._options));
  }
}
