/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { healthCheckHealthCheck } from "../funcs/healthCheckHealthCheck.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class HealthCheck extends ClientSDK {
    /**
     * Get the health of the service
     */
    async healthCheck(options?: RequestOptions): Promise<operations.HealthCheckResponseBody> {
        return unwrapAsync(healthCheckHealthCheck(this, options));
    }
}
