/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dataSignatureAggregatorAggregateSignatures } from "../funcs/dataSignatureAggregatorAggregateSignatures.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class SignatureAggregator extends ClientSDK {
  /**
   * Aggregate Signatures
   *
   * @remarks
   * Aggregates Signatures for a Warp message from Subnet validators.
   */
  async aggregateSignatures(
    request: components.SignatureAggregatorRequest,
    options?: RequestOptions & { serverURL?: string },
  ): Promise<components.SignatureAggregationResponse> {
    return unwrapAsync(dataSignatureAggregatorAggregateSignatures(
      this,
      request,
      options,
    ));
  }
}
