workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    AvaCloudSDK-OAS:
        inputs:
            - location: https://e4db-2405-201-3027-2887-c59f-283b-9808-8aac.ngrok-free.app/api-json
            - location: https://c6cd-2405-201-3027-2887-c59f-283b-9808-8aac.ngrok-free.app/api-json
        overlays:
            - location: overlays/overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/avalabs/avalabs/avacloud-sdk-oas
targets:
    avacloud-sdk:
        target: typescript
        source: AvaCloudSDK-OAS
        publish:
            npm:
                token: $npm_token
        codeSamples:
            output: ""
            registry:
                location: registry.speakeasyapi.dev/avalabs/avalabs/avacloud-sdk-ts-code-samples
