workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    AvalancheSDK-OAS:
        inputs:
            - location: https://ad39-2405-201-3027-2887-d9b-fc28-c7ec-5133.ngrok-free.app/api-json
        registry:
            location: registry.speakeasyapi.dev/avalabs/avalabs/avalanche-sdk-oas
targets:
    avalanche-sdk:
        target: typescript
        source: AvalancheSDK-OAS
        publish:
            npm:
                token: $npm_token
