/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type GetChainIdsForAddressesRequest = {
    /**
     * A comma separated list of X-Chain or P-Chain wallet addresses, starting with "avax"/"fuji", "P-avax"/"P-fuji" or "X-avax"/"X-fuji".
     */
    addresses: string;
    /**
     * Either mainnet or a testnet.
     */
    network: components.Network;
};

/** @internal */
export const GetChainIdsForAddressesRequest$inboundSchema: z.ZodType<
    GetChainIdsForAddressesRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    addresses: z.string(),
    network: components.Network$inboundSchema,
});

/** @internal */
export type GetChainIdsForAddressesRequest$Outbound = {
    addresses: string;
    network: string;
};

/** @internal */
export const GetChainIdsForAddressesRequest$outboundSchema: z.ZodType<
    GetChainIdsForAddressesRequest$Outbound,
    z.ZodTypeDef,
    GetChainIdsForAddressesRequest
> = z.object({
    addresses: z.string(),
    network: components.Network$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetChainIdsForAddressesRequest$ {
    /** @deprecated use `GetChainIdsForAddressesRequest$inboundSchema` instead. */
    export const inboundSchema = GetChainIdsForAddressesRequest$inboundSchema;
    /** @deprecated use `GetChainIdsForAddressesRequest$outboundSchema` instead. */
    export const outboundSchema = GetChainIdsForAddressesRequest$outboundSchema;
    /** @deprecated use `GetChainIdsForAddressesRequest$Outbound` instead. */
    export type Outbound = GetChainIdsForAddressesRequest$Outbound;
}
