/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const GetDeploymentTransactionServerList = [
  "https://glacier-api.avax.network",
] as const;

export type GetDeploymentTransactionGlobals = {
  /**
   * A supported EVM chain id, chain alias, or blockchain id.
   */
  chainId?: string | undefined;
};

export type GetDeploymentTransactionRequest = {
  /**
   * A supported evm chain id or blockchain id. Use the `/chains` endpoint to get a list of supported chain ids.
   */
  chainId?: string | undefined;
  /**
   * Contract address on the relevant chain.
   */
  address: string;
  /**
   * The currency that return values should use. Defaults to USD.
   */
  currency?: components.CurrencyCode | undefined;
};

/** @internal */
export const GetDeploymentTransactionGlobals$inboundSchema: z.ZodType<
  GetDeploymentTransactionGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  chainId: z.string().optional(),
});

/** @internal */
export type GetDeploymentTransactionGlobals$Outbound = {
  chainId?: string | undefined;
};

/** @internal */
export const GetDeploymentTransactionGlobals$outboundSchema: z.ZodType<
  GetDeploymentTransactionGlobals$Outbound,
  z.ZodTypeDef,
  GetDeploymentTransactionGlobals
> = z.object({
  chainId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetDeploymentTransactionGlobals$ {
  /** @deprecated use `GetDeploymentTransactionGlobals$inboundSchema` instead. */
  export const inboundSchema = GetDeploymentTransactionGlobals$inboundSchema;
  /** @deprecated use `GetDeploymentTransactionGlobals$outboundSchema` instead. */
  export const outboundSchema = GetDeploymentTransactionGlobals$outboundSchema;
  /** @deprecated use `GetDeploymentTransactionGlobals$Outbound` instead. */
  export type Outbound = GetDeploymentTransactionGlobals$Outbound;
}

export function getDeploymentTransactionGlobalsToJSON(
  getDeploymentTransactionGlobals: GetDeploymentTransactionGlobals,
): string {
  return JSON.stringify(
    GetDeploymentTransactionGlobals$outboundSchema.parse(
      getDeploymentTransactionGlobals,
    ),
  );
}

export function getDeploymentTransactionGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<GetDeploymentTransactionGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDeploymentTransactionGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDeploymentTransactionGlobals' from JSON`,
  );
}

/** @internal */
export const GetDeploymentTransactionRequest$inboundSchema: z.ZodType<
  GetDeploymentTransactionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  chainId: z.string().optional(),
  address: z.string(),
  currency: components.CurrencyCode$inboundSchema.optional(),
});

/** @internal */
export type GetDeploymentTransactionRequest$Outbound = {
  chainId?: string | undefined;
  address: string;
  currency?: string | undefined;
};

/** @internal */
export const GetDeploymentTransactionRequest$outboundSchema: z.ZodType<
  GetDeploymentTransactionRequest$Outbound,
  z.ZodTypeDef,
  GetDeploymentTransactionRequest
> = z.object({
  chainId: z.string().optional(),
  address: z.string(),
  currency: components.CurrencyCode$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetDeploymentTransactionRequest$ {
  /** @deprecated use `GetDeploymentTransactionRequest$inboundSchema` instead. */
  export const inboundSchema = GetDeploymentTransactionRequest$inboundSchema;
  /** @deprecated use `GetDeploymentTransactionRequest$outboundSchema` instead. */
  export const outboundSchema = GetDeploymentTransactionRequest$outboundSchema;
  /** @deprecated use `GetDeploymentTransactionRequest$Outbound` instead. */
  export type Outbound = GetDeploymentTransactionRequest$Outbound;
}

export function getDeploymentTransactionRequestToJSON(
  getDeploymentTransactionRequest: GetDeploymentTransactionRequest,
): string {
  return JSON.stringify(
    GetDeploymentTransactionRequest$outboundSchema.parse(
      getDeploymentTransactionRequest,
    ),
  );
}

export function getDeploymentTransactionRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetDeploymentTransactionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDeploymentTransactionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDeploymentTransactionRequest' from JSON`,
  );
}
