/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const GetMaxGpsServerList = ["http://localhost:3001"] as const;

export type GetMaxGpsRequest = {
    /**
     * From date in UNIX Timestamp.
     */
    from?: string | undefined;
    /**
     * To date in UNIX Timestamp.
     */
    to?: string | undefined;
    /**
     * For paginated responses. Value will be provided in the [nextPageStartKey] field in the response if the query has more than one page.
     */
    startKey?: string | undefined;
    /**
     * numeric chainID, 'testnet', 'mainnet', or 'total'.
     */
    chain: string;
};

/** @internal */
export const GetMaxGpsRequest$inboundSchema: z.ZodType<GetMaxGpsRequest, z.ZodTypeDef, unknown> =
    z.object({
        from: z.string().optional(),
        to: z.string().optional(),
        startKey: z.string().optional(),
        chain: z.string(),
    });

/** @internal */
export type GetMaxGpsRequest$Outbound = {
    from?: string | undefined;
    to?: string | undefined;
    startKey?: string | undefined;
    chain: string;
};

/** @internal */
export const GetMaxGpsRequest$outboundSchema: z.ZodType<
    GetMaxGpsRequest$Outbound,
    z.ZodTypeDef,
    GetMaxGpsRequest
> = z.object({
    from: z.string().optional(),
    to: z.string().optional(),
    startKey: z.string().optional(),
    chain: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetMaxGpsRequest$ {
    /** @deprecated use `GetMaxGpsRequest$inboundSchema` instead. */
    export const inboundSchema = GetMaxGpsRequest$inboundSchema;
    /** @deprecated use `GetMaxGpsRequest$outboundSchema` instead. */
    export const outboundSchema = GetMaxGpsRequest$outboundSchema;
    /** @deprecated use `GetMaxGpsRequest$Outbound` instead. */
    export type Outbound = GetMaxGpsRequest$Outbound;
}
