/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const GetRollingWindowTxCountServerList = ["http://localhost:3001"] as const;

export type GetRollingWindowTxCountGlobals = {
    chainId?: string | undefined;
};

export type GetRollingWindowTxCountRequest = {
    /**
     * A supported evm chain id. Use the `/chains` endpoint to get a list of supported chain ids.
     */
    chainId?: string | undefined;
};

/** @internal */
export const GetRollingWindowTxCountGlobals$inboundSchema: z.ZodType<
    GetRollingWindowTxCountGlobals,
    z.ZodTypeDef,
    unknown
> = z.object({
    chainId: z.string().optional(),
});

/** @internal */
export type GetRollingWindowTxCountGlobals$Outbound = {
    chainId?: string | undefined;
};

/** @internal */
export const GetRollingWindowTxCountGlobals$outboundSchema: z.ZodType<
    GetRollingWindowTxCountGlobals$Outbound,
    z.ZodTypeDef,
    GetRollingWindowTxCountGlobals
> = z.object({
    chainId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetRollingWindowTxCountGlobals$ {
    /** @deprecated use `GetRollingWindowTxCountGlobals$inboundSchema` instead. */
    export const inboundSchema = GetRollingWindowTxCountGlobals$inboundSchema;
    /** @deprecated use `GetRollingWindowTxCountGlobals$outboundSchema` instead. */
    export const outboundSchema = GetRollingWindowTxCountGlobals$outboundSchema;
    /** @deprecated use `GetRollingWindowTxCountGlobals$Outbound` instead. */
    export type Outbound = GetRollingWindowTxCountGlobals$Outbound;
}

/** @internal */
export const GetRollingWindowTxCountRequest$inboundSchema: z.ZodType<
    GetRollingWindowTxCountRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    chainId: z.string().optional(),
});

/** @internal */
export type GetRollingWindowTxCountRequest$Outbound = {
    chainId?: string | undefined;
};

/** @internal */
export const GetRollingWindowTxCountRequest$outboundSchema: z.ZodType<
    GetRollingWindowTxCountRequest$Outbound,
    z.ZodTypeDef,
    GetRollingWindowTxCountRequest
> = z.object({
    chainId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetRollingWindowTxCountRequest$ {
    /** @deprecated use `GetRollingWindowTxCountRequest$inboundSchema` instead. */
    export const inboundSchema = GetRollingWindowTxCountRequest$inboundSchema;
    /** @deprecated use `GetRollingWindowTxCountRequest$outboundSchema` instead. */
    export const outboundSchema = GetRollingWindowTxCountRequest$outboundSchema;
    /** @deprecated use `GetRollingWindowTxCountRequest$Outbound` instead. */
    export type Outbound = GetRollingWindowTxCountRequest$Outbound;
}
