/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ListAddressChainsServerList = [
  "https://glacier-api.avax.network",
] as const;

export type ListAddressChainsRequest = {
  /**
   * A wallet address.
   */
  address: string;
};

/** @internal */
export const ListAddressChainsRequest$inboundSchema: z.ZodType<
  ListAddressChainsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  address: z.string(),
});

/** @internal */
export type ListAddressChainsRequest$Outbound = {
  address: string;
};

/** @internal */
export const ListAddressChainsRequest$outboundSchema: z.ZodType<
  ListAddressChainsRequest$Outbound,
  z.ZodTypeDef,
  ListAddressChainsRequest
> = z.object({
  address: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListAddressChainsRequest$ {
  /** @deprecated use `ListAddressChainsRequest$inboundSchema` instead. */
  export const inboundSchema = ListAddressChainsRequest$inboundSchema;
  /** @deprecated use `ListAddressChainsRequest$outboundSchema` instead. */
  export const outboundSchema = ListAddressChainsRequest$outboundSchema;
  /** @deprecated use `ListAddressChainsRequest$Outbound` instead. */
  export type Outbound = ListAddressChainsRequest$Outbound;
}

export function listAddressChainsRequestToJSON(
  listAddressChainsRequest: ListAddressChainsRequest,
): string {
  return JSON.stringify(
    ListAddressChainsRequest$outboundSchema.parse(listAddressChainsRequest),
  );
}

export function listAddressChainsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListAddressChainsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAddressChainsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAddressChainsRequest' from JSON`,
  );
}
