/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ListLatestXChainVerticesGlobals = {
    /**
     * A supported network type mainnet or a testnet.
     */
    network?: components.GlobalParamNetwork | undefined;
};

export type ListLatestXChainVerticesRequest = {
    /**
     * A page token, received from a previous list call. Provide this to retrieve the subsequent page.
     */
    pageToken?: string | undefined;
    /**
     * The maximum number of items to return. The minimum page size is 1. The maximum pageSize is 100.
     */
    pageSize?: number | undefined;
    /**
     * A primary network blockchain id or alias.
     */
    blockchainId: components.XChainId;
    /**
     * Either mainnet or a testnet.
     */
    network?: components.GlobalParamNetwork | undefined;
};

export type ListLatestXChainVerticesResponse = {
    result: components.ListXChainVerticesResponse;
};

/** @internal */
export const ListLatestXChainVerticesGlobals$inboundSchema: z.ZodType<
    ListLatestXChainVerticesGlobals,
    z.ZodTypeDef,
    unknown
> = z.object({
    network: components.GlobalParamNetwork$inboundSchema.optional(),
});

/** @internal */
export type ListLatestXChainVerticesGlobals$Outbound = {
    network?: string | undefined;
};

/** @internal */
export const ListLatestXChainVerticesGlobals$outboundSchema: z.ZodType<
    ListLatestXChainVerticesGlobals$Outbound,
    z.ZodTypeDef,
    ListLatestXChainVerticesGlobals
> = z.object({
    network: components.GlobalParamNetwork$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListLatestXChainVerticesGlobals$ {
    /** @deprecated use `ListLatestXChainVerticesGlobals$inboundSchema` instead. */
    export const inboundSchema = ListLatestXChainVerticesGlobals$inboundSchema;
    /** @deprecated use `ListLatestXChainVerticesGlobals$outboundSchema` instead. */
    export const outboundSchema = ListLatestXChainVerticesGlobals$outboundSchema;
    /** @deprecated use `ListLatestXChainVerticesGlobals$Outbound` instead. */
    export type Outbound = ListLatestXChainVerticesGlobals$Outbound;
}

/** @internal */
export const ListLatestXChainVerticesRequest$inboundSchema: z.ZodType<
    ListLatestXChainVerticesRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    pageToken: z.string().optional(),
    pageSize: z.number().int().default(10),
    blockchainId: components.XChainId$inboundSchema,
    network: components.GlobalParamNetwork$inboundSchema.optional(),
});

/** @internal */
export type ListLatestXChainVerticesRequest$Outbound = {
    pageToken?: string | undefined;
    pageSize: number;
    blockchainId: string;
    network?: string | undefined;
};

/** @internal */
export const ListLatestXChainVerticesRequest$outboundSchema: z.ZodType<
    ListLatestXChainVerticesRequest$Outbound,
    z.ZodTypeDef,
    ListLatestXChainVerticesRequest
> = z.object({
    pageToken: z.string().optional(),
    pageSize: z.number().int().default(10),
    blockchainId: components.XChainId$outboundSchema,
    network: components.GlobalParamNetwork$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListLatestXChainVerticesRequest$ {
    /** @deprecated use `ListLatestXChainVerticesRequest$inboundSchema` instead. */
    export const inboundSchema = ListLatestXChainVerticesRequest$inboundSchema;
    /** @deprecated use `ListLatestXChainVerticesRequest$outboundSchema` instead. */
    export const outboundSchema = ListLatestXChainVerticesRequest$outboundSchema;
    /** @deprecated use `ListLatestXChainVerticesRequest$Outbound` instead. */
    export type Outbound = ListLatestXChainVerticesRequest$Outbound;
}

/** @internal */
export const ListLatestXChainVerticesResponse$inboundSchema: z.ZodType<
    ListLatestXChainVerticesResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        Result: components.ListXChainVerticesResponse$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            Result: "result",
        });
    });

/** @internal */
export type ListLatestXChainVerticesResponse$Outbound = {
    Result: components.ListXChainVerticesResponse$Outbound;
};

/** @internal */
export const ListLatestXChainVerticesResponse$outboundSchema: z.ZodType<
    ListLatestXChainVerticesResponse$Outbound,
    z.ZodTypeDef,
    ListLatestXChainVerticesResponse
> = z
    .object({
        result: components.ListXChainVerticesResponse$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            result: "Result",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListLatestXChainVerticesResponse$ {
    /** @deprecated use `ListLatestXChainVerticesResponse$inboundSchema` instead. */
    export const inboundSchema = ListLatestXChainVerticesResponse$inboundSchema;
    /** @deprecated use `ListLatestXChainVerticesResponse$outboundSchema` instead. */
    export const outboundSchema = ListLatestXChainVerticesResponse$outboundSchema;
    /** @deprecated use `ListLatestXChainVerticesResponse$Outbound` instead. */
    export type Outbound = ListLatestXChainVerticesResponse$Outbound;
}
