/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export const PostTransactionExportJobServerList = ["https://glacier-api.avax.network"] as const;

export type PostTransactionExportJobRequestBody =
    | components.CreateEvmTransactionExportRequest
    | components.CreatePrimaryNetworkTransactionExportRequest;

/** @internal */
export const PostTransactionExportJobRequestBody$inboundSchema: z.ZodType<
    PostTransactionExportJobRequestBody,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.CreateEvmTransactionExportRequest$inboundSchema,
    components.CreatePrimaryNetworkTransactionExportRequest$inboundSchema,
]);

/** @internal */
export type PostTransactionExportJobRequestBody$Outbound =
    | components.CreateEvmTransactionExportRequest$Outbound
    | components.CreatePrimaryNetworkTransactionExportRequest$Outbound;

/** @internal */
export const PostTransactionExportJobRequestBody$outboundSchema: z.ZodType<
    PostTransactionExportJobRequestBody$Outbound,
    z.ZodTypeDef,
    PostTransactionExportJobRequestBody
> = z.union([
    components.CreateEvmTransactionExportRequest$outboundSchema,
    components.CreatePrimaryNetworkTransactionExportRequest$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostTransactionExportJobRequestBody$ {
    /** @deprecated use `PostTransactionExportJobRequestBody$inboundSchema` instead. */
    export const inboundSchema = PostTransactionExportJobRequestBody$inboundSchema;
    /** @deprecated use `PostTransactionExportJobRequestBody$outboundSchema` instead. */
    export const outboundSchema = PostTransactionExportJobRequestBody$outboundSchema;
    /** @deprecated use `PostTransactionExportJobRequestBody$Outbound` instead. */
    export type Outbound = PostTransactionExportJobRequestBody$Outbound;
}
