/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    PrimaryNetworkAssetType,
    PrimaryNetworkAssetType$inboundSchema,
    PrimaryNetworkAssetType$outboundSchema,
} from "./primarynetworkassettype.js";
import * as z from "zod";

export type AggregatedAssetAmount = {
    /**
     * Unique ID for an asset.
     */
    assetId: string;
    /**
     * Name of this asset.
     */
    name: string;
    /**
     * Symbol for this asset (max 4 characters).
     */
    symbol: string;
    /**
     * Denomination of this asset to represent fungibility.
     */
    denomination: number;
    /**
     * Type of asset like SECP256K1 or NFT.
     */
    type: PrimaryNetworkAssetType;
    /**
     * Amount of the asset.
     */
    amount: string;
    utxoCount: number;
};

/** @internal */
export const AggregatedAssetAmount$inboundSchema: z.ZodType<
    AggregatedAssetAmount,
    z.ZodTypeDef,
    unknown
> = z.object({
    assetId: z.string(),
    name: z.string(),
    symbol: z.string(),
    denomination: z.number(),
    type: PrimaryNetworkAssetType$inboundSchema,
    amount: z.string(),
    utxoCount: z.number(),
});

/** @internal */
export type AggregatedAssetAmount$Outbound = {
    assetId: string;
    name: string;
    symbol: string;
    denomination: number;
    type: string;
    amount: string;
    utxoCount: number;
};

/** @internal */
export const AggregatedAssetAmount$outboundSchema: z.ZodType<
    AggregatedAssetAmount$Outbound,
    z.ZodTypeDef,
    AggregatedAssetAmount
> = z.object({
    assetId: z.string(),
    name: z.string(),
    symbol: z.string(),
    denomination: z.number(),
    type: PrimaryNetworkAssetType$outboundSchema,
    amount: z.string(),
    utxoCount: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AggregatedAssetAmount$ {
    /** @deprecated use `AggregatedAssetAmount$inboundSchema` instead. */
    export const inboundSchema = AggregatedAssetAmount$inboundSchema;
    /** @deprecated use `AggregatedAssetAmount$outboundSchema` instead. */
    export const outboundSchema = AggregatedAssetAmount$outboundSchema;
    /** @deprecated use `AggregatedAssetAmount$Outbound` instead. */
    export type Outbound = AggregatedAssetAmount$Outbound;
}
