/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";
import {
  DateRangeNftHoldersParam,
  DateRangeNftHoldersParam$inboundSchema,
  DateRangeNftHoldersParam$Outbound,
  DateRangeNftHoldersParam$outboundSchema,
} from "./daterangenftholdersparam.js";
import {
  TimestampRangeNftHoldersParam,
  TimestampRangeNftHoldersParam$inboundSchema,
  TimestampRangeNftHoldersParam$Outbound,
  TimestampRangeNftHoldersParam$outboundSchema,
} from "./timestamprangenftholdersparam.js";

export const AnyTimeNftHoldersQueryDtoType = {
  AnyTimeNftHolders: "AnyTimeNftHolders",
} as const;
export type AnyTimeNftHoldersQueryDtoType = ClosedEnum<
  typeof AnyTimeNftHoldersQueryDtoType
>;

export type AnyTimeNftHoldersQueryDtoParams =
  | TimestampRangeNftHoldersParam
  | DateRangeNftHoldersParam;

export type AnyTimeNftHoldersQueryDto = {
  id: string;
  type: AnyTimeNftHoldersQueryDtoType;
  params: TimestampRangeNftHoldersParam | DateRangeNftHoldersParam;
};

/** @internal */
export const AnyTimeNftHoldersQueryDtoType$inboundSchema: z.ZodNativeEnum<
  typeof AnyTimeNftHoldersQueryDtoType
> = z.nativeEnum(AnyTimeNftHoldersQueryDtoType);

/** @internal */
export const AnyTimeNftHoldersQueryDtoType$outboundSchema: z.ZodNativeEnum<
  typeof AnyTimeNftHoldersQueryDtoType
> = AnyTimeNftHoldersQueryDtoType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AnyTimeNftHoldersQueryDtoType$ {
  /** @deprecated use `AnyTimeNftHoldersQueryDtoType$inboundSchema` instead. */
  export const inboundSchema = AnyTimeNftHoldersQueryDtoType$inboundSchema;
  /** @deprecated use `AnyTimeNftHoldersQueryDtoType$outboundSchema` instead. */
  export const outboundSchema = AnyTimeNftHoldersQueryDtoType$outboundSchema;
}

/** @internal */
export const AnyTimeNftHoldersQueryDtoParams$inboundSchema: z.ZodType<
  AnyTimeNftHoldersQueryDtoParams,
  z.ZodTypeDef,
  unknown
> = z.union([
  TimestampRangeNftHoldersParam$inboundSchema,
  DateRangeNftHoldersParam$inboundSchema,
]);

/** @internal */
export type AnyTimeNftHoldersQueryDtoParams$Outbound =
  | TimestampRangeNftHoldersParam$Outbound
  | DateRangeNftHoldersParam$Outbound;

/** @internal */
export const AnyTimeNftHoldersQueryDtoParams$outboundSchema: z.ZodType<
  AnyTimeNftHoldersQueryDtoParams$Outbound,
  z.ZodTypeDef,
  AnyTimeNftHoldersQueryDtoParams
> = z.union([
  TimestampRangeNftHoldersParam$outboundSchema,
  DateRangeNftHoldersParam$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AnyTimeNftHoldersQueryDtoParams$ {
  /** @deprecated use `AnyTimeNftHoldersQueryDtoParams$inboundSchema` instead. */
  export const inboundSchema = AnyTimeNftHoldersQueryDtoParams$inboundSchema;
  /** @deprecated use `AnyTimeNftHoldersQueryDtoParams$outboundSchema` instead. */
  export const outboundSchema = AnyTimeNftHoldersQueryDtoParams$outboundSchema;
  /** @deprecated use `AnyTimeNftHoldersQueryDtoParams$Outbound` instead. */
  export type Outbound = AnyTimeNftHoldersQueryDtoParams$Outbound;
}

/** @internal */
export const AnyTimeNftHoldersQueryDto$inboundSchema: z.ZodType<
  AnyTimeNftHoldersQueryDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: AnyTimeNftHoldersQueryDtoType$inboundSchema,
  params: z.union([
    TimestampRangeNftHoldersParam$inboundSchema,
    DateRangeNftHoldersParam$inboundSchema,
  ]),
});

/** @internal */
export type AnyTimeNftHoldersQueryDto$Outbound = {
  id: string;
  type: string;
  params:
    | TimestampRangeNftHoldersParam$Outbound
    | DateRangeNftHoldersParam$Outbound;
};

/** @internal */
export const AnyTimeNftHoldersQueryDto$outboundSchema: z.ZodType<
  AnyTimeNftHoldersQueryDto$Outbound,
  z.ZodTypeDef,
  AnyTimeNftHoldersQueryDto
> = z.object({
  id: z.string(),
  type: AnyTimeNftHoldersQueryDtoType$outboundSchema,
  params: z.union([
    TimestampRangeNftHoldersParam$outboundSchema,
    DateRangeNftHoldersParam$outboundSchema,
  ]),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AnyTimeNftHoldersQueryDto$ {
  /** @deprecated use `AnyTimeNftHoldersQueryDto$inboundSchema` instead. */
  export const inboundSchema = AnyTimeNftHoldersQueryDto$inboundSchema;
  /** @deprecated use `AnyTimeNftHoldersQueryDto$outboundSchema` instead. */
  export const outboundSchema = AnyTimeNftHoldersQueryDto$outboundSchema;
  /** @deprecated use `AnyTimeNftHoldersQueryDto$Outbound` instead. */
  export type Outbound = AnyTimeNftHoldersQueryDto$Outbound;
}
