/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PrimaryNetworkAssetType,
  PrimaryNetworkAssetType$inboundSchema,
  PrimaryNetworkAssetType$outboundSchema,
} from "./primarynetworkassettype.js";

export type AssetAmount = {
  /**
   * Unique ID for an asset.
   */
  assetId: string;
  /**
   * Name of this asset.
   */
  name: string;
  /**
   * Symbol for this asset (max 4 characters).
   */
  symbol: string;
  /**
   * Denomination of this asset to represent fungibility.
   */
  denomination: number;
  /**
   * Type of asset like SECP256K1 or NFT.
   */
  type: PrimaryNetworkAssetType;
  /**
   * Amount of the asset.
   */
  amount: string;
};

/** @internal */
export const AssetAmount$inboundSchema: z.ZodType<
  AssetAmount,
  z.ZodTypeDef,
  unknown
> = z.object({
  assetId: z.string(),
  name: z.string(),
  symbol: z.string(),
  denomination: z.number(),
  type: PrimaryNetworkAssetType$inboundSchema,
  amount: z.string(),
});

/** @internal */
export type AssetAmount$Outbound = {
  assetId: string;
  name: string;
  symbol: string;
  denomination: number;
  type: string;
  amount: string;
};

/** @internal */
export const AssetAmount$outboundSchema: z.ZodType<
  AssetAmount$Outbound,
  z.ZodTypeDef,
  AssetAmount
> = z.object({
  assetId: z.string(),
  name: z.string(),
  symbol: z.string(),
  denomination: z.number(),
  type: PrimaryNetworkAssetType$outboundSchema,
  amount: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AssetAmount$ {
  /** @deprecated use `AssetAmount$inboundSchema` instead. */
  export const inboundSchema = AssetAmount$inboundSchema;
  /** @deprecated use `AssetAmount$outboundSchema` instead. */
  export const outboundSchema = AssetAmount$outboundSchema;
  /** @deprecated use `AssetAmount$Outbound` instead. */
  export type Outbound = AssetAmount$Outbound;
}

export function assetAmountToJSON(assetAmount: AssetAmount): string {
  return JSON.stringify(AssetAmount$outboundSchema.parse(assetAmount));
}

export function assetAmountFromJSON(
  jsonString: string,
): SafeParseResult<AssetAmount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssetAmount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssetAmount' from JSON`,
  );
}
