/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Erc721Token,
  Erc721Token$inboundSchema,
  Erc721Token$Outbound,
  Erc721Token$outboundSchema,
} from "./erc721token.js";
import {
  RichAddress,
  RichAddress$inboundSchema,
  RichAddress$Outbound,
  RichAddress$outboundSchema,
} from "./richaddress.js";

export type Erc721TransferDetails = {
  from: RichAddress;
  to: RichAddress;
  logIndex: number;
  erc721Token: Erc721Token;
};

/** @internal */
export const Erc721TransferDetails$inboundSchema: z.ZodType<
  Erc721TransferDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  from: RichAddress$inboundSchema,
  to: RichAddress$inboundSchema,
  logIndex: z.number(),
  erc721Token: Erc721Token$inboundSchema,
});

/** @internal */
export type Erc721TransferDetails$Outbound = {
  from: RichAddress$Outbound;
  to: RichAddress$Outbound;
  logIndex: number;
  erc721Token: Erc721Token$Outbound;
};

/** @internal */
export const Erc721TransferDetails$outboundSchema: z.ZodType<
  Erc721TransferDetails$Outbound,
  z.ZodTypeDef,
  Erc721TransferDetails
> = z.object({
  from: RichAddress$outboundSchema,
  to: RichAddress$outboundSchema,
  logIndex: z.number(),
  erc721Token: Erc721Token$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Erc721TransferDetails$ {
  /** @deprecated use `Erc721TransferDetails$inboundSchema` instead. */
  export const inboundSchema = Erc721TransferDetails$inboundSchema;
  /** @deprecated use `Erc721TransferDetails$outboundSchema` instead. */
  export const outboundSchema = Erc721TransferDetails$outboundSchema;
  /** @deprecated use `Erc721TransferDetails$Outbound` instead. */
  export type Outbound = Erc721TransferDetails$Outbound;
}

export function erc721TransferDetailsToJSON(
  erc721TransferDetails: Erc721TransferDetails,
): string {
  return JSON.stringify(
    Erc721TransferDetails$outboundSchema.parse(erc721TransferDetails),
  );
}

export function erc721TransferDetailsFromJSON(
  jsonString: string,
): SafeParseResult<Erc721TransferDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Erc721TransferDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Erc721TransferDetails' from JSON`,
  );
}
