/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const LegacyNetworks = {
    Mainnet: "mainnet",
    Fuji: "fuji",
} as const;
export type LegacyNetworks = ClosedEnum<typeof LegacyNetworks>;

/** @internal */
export const LegacyNetworks$inboundSchema: z.ZodNativeEnum<typeof LegacyNetworks> =
    z.nativeEnum(LegacyNetworks);

/** @internal */
export const LegacyNetworks$outboundSchema: z.ZodNativeEnum<typeof LegacyNetworks> =
    LegacyNetworks$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LegacyNetworks$ {
    /** @deprecated use `LegacyNetworks$inboundSchema` instead. */
    export const inboundSchema = LegacyNetworks$inboundSchema;
    /** @deprecated use `LegacyNetworks$outboundSchema` instead. */
    export const outboundSchema = LegacyNetworks$outboundSchema;
}
