/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    ChainInfo,
    ChainInfo$inboundSchema,
    ChainInfo$Outbound,
    ChainInfo$outboundSchema,
} from "./chaininfo.js";
import * as z from "zod";

export type ListChainsResponse = {
    chains: Array<ChainInfo>;
};

/** @internal */
export const ListChainsResponse$inboundSchema: z.ZodType<
    ListChainsResponse,
    z.ZodTypeDef,
    unknown
> = z.object({
    chains: z.array(ChainInfo$inboundSchema),
});

/** @internal */
export type ListChainsResponse$Outbound = {
    chains: Array<ChainInfo$Outbound>;
};

/** @internal */
export const ListChainsResponse$outboundSchema: z.ZodType<
    ListChainsResponse$Outbound,
    z.ZodTypeDef,
    ListChainsResponse
> = z.object({
    chains: z.array(ChainInfo$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListChainsResponse$ {
    /** @deprecated use `ListChainsResponse$inboundSchema` instead. */
    export const inboundSchema = ListChainsResponse$inboundSchema;
    /** @deprecated use `ListChainsResponse$outboundSchema` instead. */
    export const outboundSchema = ListChainsResponse$outboundSchema;
    /** @deprecated use `ListChainsResponse$Outbound` instead. */
    export type Outbound = ListChainsResponse$Outbound;
}
