/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    Erc721TokenBalance,
    Erc721TokenBalance$inboundSchema,
    Erc721TokenBalance$Outbound,
    Erc721TokenBalance$outboundSchema,
} from "./erc721tokenbalance.js";
import * as z from "zod";

export type ListErc721BalancesResponse = {
    /**
     * A token, which can be sent as `pageToken` to retrieve the next page. If this field is omitted or empty, there are no subsequent pages.
     */
    nextPageToken?: string | undefined;
    /**
     * The list of ERC-721 token balances for the address.
     */
    erc721TokenBalances: Array<Erc721TokenBalance>;
};

/** @internal */
export const ListErc721BalancesResponse$inboundSchema: z.ZodType<
    ListErc721BalancesResponse,
    z.ZodTypeDef,
    unknown
> = z.object({
    nextPageToken: z.string().optional(),
    erc721TokenBalances: z.array(Erc721TokenBalance$inboundSchema),
});

/** @internal */
export type ListErc721BalancesResponse$Outbound = {
    nextPageToken?: string | undefined;
    erc721TokenBalances: Array<Erc721TokenBalance$Outbound>;
};

/** @internal */
export const ListErc721BalancesResponse$outboundSchema: z.ZodType<
    ListErc721BalancesResponse$Outbound,
    z.ZodTypeDef,
    ListErc721BalancesResponse
> = z.object({
    nextPageToken: z.string().optional(),
    erc721TokenBalances: z.array(Erc721TokenBalance$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListErc721BalancesResponse$ {
    /** @deprecated use `ListErc721BalancesResponse$inboundSchema` instead. */
    export const inboundSchema = ListErc721BalancesResponse$inboundSchema;
    /** @deprecated use `ListErc721BalancesResponse$outboundSchema` instead. */
    export const outboundSchema = ListErc721BalancesResponse$outboundSchema;
    /** @deprecated use `ListErc721BalancesResponse$Outbound` instead. */
    export type Outbound = ListErc721BalancesResponse$Outbound;
}
