/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CChainAtomicBalances,
  CChainAtomicBalances$inboundSchema,
  CChainAtomicBalances$Outbound,
  CChainAtomicBalances$outboundSchema,
} from "./cchainatomicbalances.js";
import {
  PrimaryNetworkChainInfo,
  PrimaryNetworkChainInfo$inboundSchema,
  PrimaryNetworkChainInfo$Outbound,
  PrimaryNetworkChainInfo$outboundSchema,
} from "./primarynetworkchaininfo.js";

export type ListCChainAtomicBalancesResponse = {
  balances: CChainAtomicBalances;
  chainInfo: PrimaryNetworkChainInfo;
};

/** @internal */
export const ListCChainAtomicBalancesResponse$inboundSchema: z.ZodType<
  ListCChainAtomicBalancesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  balances: CChainAtomicBalances$inboundSchema,
  chainInfo: PrimaryNetworkChainInfo$inboundSchema,
});

/** @internal */
export type ListCChainAtomicBalancesResponse$Outbound = {
  balances: CChainAtomicBalances$Outbound;
  chainInfo: PrimaryNetworkChainInfo$Outbound;
};

/** @internal */
export const ListCChainAtomicBalancesResponse$outboundSchema: z.ZodType<
  ListCChainAtomicBalancesResponse$Outbound,
  z.ZodTypeDef,
  ListCChainAtomicBalancesResponse
> = z.object({
  balances: CChainAtomicBalances$outboundSchema,
  chainInfo: PrimaryNetworkChainInfo$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListCChainAtomicBalancesResponse$ {
  /** @deprecated use `ListCChainAtomicBalancesResponse$inboundSchema` instead. */
  export const inboundSchema = ListCChainAtomicBalancesResponse$inboundSchema;
  /** @deprecated use `ListCChainAtomicBalancesResponse$outboundSchema` instead. */
  export const outboundSchema = ListCChainAtomicBalancesResponse$outboundSchema;
  /** @deprecated use `ListCChainAtomicBalancesResponse$Outbound` instead. */
  export type Outbound = ListCChainAtomicBalancesResponse$Outbound;
}
