/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ActiveValidatorDetails,
  ActiveValidatorDetails$inboundSchema,
  ActiveValidatorDetails$Outbound,
  ActiveValidatorDetails$outboundSchema,
} from "./activevalidatordetails.js";
import {
  CompletedValidatorDetails,
  CompletedValidatorDetails$inboundSchema,
  CompletedValidatorDetails$Outbound,
  CompletedValidatorDetails$outboundSchema,
} from "./completedvalidatordetails.js";
import {
  PendingValidatorDetails,
  PendingValidatorDetails$inboundSchema,
  PendingValidatorDetails$Outbound,
  PendingValidatorDetails$outboundSchema,
} from "./pendingvalidatordetails.js";
import {
  RemovedValidatorDetails,
  RemovedValidatorDetails$inboundSchema,
  RemovedValidatorDetails$Outbound,
  RemovedValidatorDetails$outboundSchema,
} from "./removedvalidatordetails.js";

export type Validators =
  | (PendingValidatorDetails & { validationStatus: "pending" })
  | (RemovedValidatorDetails & { validationStatus: "removed" })
  | (CompletedValidatorDetails & { validationStatus: "completed" })
  | (ActiveValidatorDetails & { validationStatus: "active" });

export type ListValidatorDetailsResponse = {
  /**
   * A token, which can be sent as `pageToken` to retrieve the next page. If this field is omitted or empty, there are no subsequent pages.
   */
  nextPageToken?: string | undefined;
  /**
   * The list of validator Details.
   */
  validators: Array<
    | (PendingValidatorDetails & { validationStatus: "pending" })
    | (RemovedValidatorDetails & { validationStatus: "removed" })
    | (CompletedValidatorDetails & { validationStatus: "completed" })
    | (ActiveValidatorDetails & { validationStatus: "active" })
  >;
};

/** @internal */
export const Validators$inboundSchema: z.ZodType<
  Validators,
  z.ZodTypeDef,
  unknown
> = z.union([
  PendingValidatorDetails$inboundSchema.and(
    z.object({ validationStatus: z.literal("pending") }).transform((v) => ({
      validationStatus: v.validationStatus,
    })),
  ),
  RemovedValidatorDetails$inboundSchema.and(
    z.object({ validationStatus: z.literal("removed") }).transform((v) => ({
      validationStatus: v.validationStatus,
    })),
  ),
  CompletedValidatorDetails$inboundSchema.and(
    z.object({ validationStatus: z.literal("completed") }).transform((v) => ({
      validationStatus: v.validationStatus,
    })),
  ),
  ActiveValidatorDetails$inboundSchema.and(
    z.object({ validationStatus: z.literal("active") }).transform((v) => ({
      validationStatus: v.validationStatus,
    })),
  ),
]);

/** @internal */
export type Validators$Outbound =
  | (PendingValidatorDetails$Outbound & { validationStatus: "pending" })
  | (RemovedValidatorDetails$Outbound & { validationStatus: "removed" })
  | (CompletedValidatorDetails$Outbound & { validationStatus: "completed" })
  | (ActiveValidatorDetails$Outbound & { validationStatus: "active" });

/** @internal */
export const Validators$outboundSchema: z.ZodType<
  Validators$Outbound,
  z.ZodTypeDef,
  Validators
> = z.union([
  PendingValidatorDetails$outboundSchema.and(
    z.object({ validationStatus: z.literal("pending") }).transform((v) => ({
      validationStatus: v.validationStatus,
    })),
  ),
  RemovedValidatorDetails$outboundSchema.and(
    z.object({ validationStatus: z.literal("removed") }).transform((v) => ({
      validationStatus: v.validationStatus,
    })),
  ),
  CompletedValidatorDetails$outboundSchema.and(
    z.object({ validationStatus: z.literal("completed") }).transform((v) => ({
      validationStatus: v.validationStatus,
    })),
  ),
  ActiveValidatorDetails$outboundSchema.and(
    z.object({ validationStatus: z.literal("active") }).transform((v) => ({
      validationStatus: v.validationStatus,
    })),
  ),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Validators$ {
  /** @deprecated use `Validators$inboundSchema` instead. */
  export const inboundSchema = Validators$inboundSchema;
  /** @deprecated use `Validators$outboundSchema` instead. */
  export const outboundSchema = Validators$outboundSchema;
  /** @deprecated use `Validators$Outbound` instead. */
  export type Outbound = Validators$Outbound;
}

export function validatorsToJSON(validators: Validators): string {
  return JSON.stringify(Validators$outboundSchema.parse(validators));
}

export function validatorsFromJSON(
  jsonString: string,
): SafeParseResult<Validators, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Validators$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Validators' from JSON`,
  );
}

/** @internal */
export const ListValidatorDetailsResponse$inboundSchema: z.ZodType<
  ListValidatorDetailsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  nextPageToken: z.string().optional(),
  validators: z.array(
    z.union([
      PendingValidatorDetails$inboundSchema.and(
        z.object({ validationStatus: z.literal("pending") }).transform((v) => ({
          validationStatus: v.validationStatus,
        })),
      ),
      RemovedValidatorDetails$inboundSchema.and(
        z.object({ validationStatus: z.literal("removed") }).transform((v) => ({
          validationStatus: v.validationStatus,
        })),
      ),
      CompletedValidatorDetails$inboundSchema.and(
        z.object({ validationStatus: z.literal("completed") }).transform((
          v,
        ) => ({ validationStatus: v.validationStatus })),
      ),
      ActiveValidatorDetails$inboundSchema.and(
        z.object({ validationStatus: z.literal("active") }).transform((v) => ({
          validationStatus: v.validationStatus,
        })),
      ),
    ]),
  ),
});

/** @internal */
export type ListValidatorDetailsResponse$Outbound = {
  nextPageToken?: string | undefined;
  validators: Array<
    | (PendingValidatorDetails$Outbound & { validationStatus: "pending" })
    | (RemovedValidatorDetails$Outbound & { validationStatus: "removed" })
    | (CompletedValidatorDetails$Outbound & { validationStatus: "completed" })
    | (ActiveValidatorDetails$Outbound & { validationStatus: "active" })
  >;
};

/** @internal */
export const ListValidatorDetailsResponse$outboundSchema: z.ZodType<
  ListValidatorDetailsResponse$Outbound,
  z.ZodTypeDef,
  ListValidatorDetailsResponse
> = z.object({
  nextPageToken: z.string().optional(),
  validators: z.array(
    z.union([
      PendingValidatorDetails$outboundSchema.and(
        z.object({ validationStatus: z.literal("pending") }).transform((v) => ({
          validationStatus: v.validationStatus,
        })),
      ),
      RemovedValidatorDetails$outboundSchema.and(
        z.object({ validationStatus: z.literal("removed") }).transform((v) => ({
          validationStatus: v.validationStatus,
        })),
      ),
      CompletedValidatorDetails$outboundSchema.and(
        z.object({ validationStatus: z.literal("completed") }).transform((
          v,
        ) => ({ validationStatus: v.validationStatus })),
      ),
      ActiveValidatorDetails$outboundSchema.and(
        z.object({ validationStatus: z.literal("active") }).transform((v) => ({
          validationStatus: v.validationStatus,
        })),
      ),
    ]),
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListValidatorDetailsResponse$ {
  /** @deprecated use `ListValidatorDetailsResponse$inboundSchema` instead. */
  export const inboundSchema = ListValidatorDetailsResponse$inboundSchema;
  /** @deprecated use `ListValidatorDetailsResponse$outboundSchema` instead. */
  export const outboundSchema = ListValidatorDetailsResponse$outboundSchema;
  /** @deprecated use `ListValidatorDetailsResponse$Outbound` instead. */
  export type Outbound = ListValidatorDetailsResponse$Outbound;
}

export function listValidatorDetailsResponseToJSON(
  listValidatorDetailsResponse: ListValidatorDetailsResponse,
): string {
  return JSON.stringify(
    ListValidatorDetailsResponse$outboundSchema.parse(
      listValidatorDetailsResponse,
    ),
  );
}

export function listValidatorDetailsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListValidatorDetailsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListValidatorDetailsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListValidatorDetailsResponse' from JSON`,
  );
}
