/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  Money,
  Money$inboundSchema,
  Money$Outbound,
  Money$outboundSchema,
} from "./money.js";
import {
  NetworkToken,
  NetworkToken$inboundSchema,
  NetworkToken$Outbound,
  NetworkToken$outboundSchema,
} from "./networktoken.js";

export type NetworkTokenDetails = {
  networkToken: NetworkToken;
  /**
   * The current token price, if available.
   */
  currentPrice?: Money | undefined;
  /**
   * The historical token price at the time the transaction occured, if available. Note, this is only provided if the transaction occured more than 24 hours ago.
   */
  historicalPrice?: Money | undefined;
};

/** @internal */
export const NetworkTokenDetails$inboundSchema: z.ZodType<
  NetworkTokenDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  networkToken: NetworkToken$inboundSchema,
  currentPrice: Money$inboundSchema.optional(),
  historicalPrice: Money$inboundSchema.optional(),
});

/** @internal */
export type NetworkTokenDetails$Outbound = {
  networkToken: NetworkToken$Outbound;
  currentPrice?: Money$Outbound | undefined;
  historicalPrice?: Money$Outbound | undefined;
};

/** @internal */
export const NetworkTokenDetails$outboundSchema: z.ZodType<
  NetworkTokenDetails$Outbound,
  z.ZodTypeDef,
  NetworkTokenDetails
> = z.object({
  networkToken: NetworkToken$outboundSchema,
  currentPrice: Money$outboundSchema.optional(),
  historicalPrice: Money$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NetworkTokenDetails$ {
  /** @deprecated use `NetworkTokenDetails$inboundSchema` instead. */
  export const inboundSchema = NetworkTokenDetails$inboundSchema;
  /** @deprecated use `NetworkTokenDetails$outboundSchema` instead. */
  export const outboundSchema = NetworkTokenDetails$outboundSchema;
  /** @deprecated use `NetworkTokenDetails$Outbound` instead. */
  export type Outbound = NetworkTokenDetails$Outbound;
}
