/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const PChainTransactionType = {
  AddValidatorTx: "AddValidatorTx",
  AddSubnetValidatorTx: "AddSubnetValidatorTx",
  AddDelegatorTx: "AddDelegatorTx",
  CreateChainTx: "CreateChainTx",
  CreateSubnetTx: "CreateSubnetTx",
  ImportTx: "ImportTx",
  ExportTx: "ExportTx",
  AdvanceTimeTx: "AdvanceTimeTx",
  RewardValidatorTx: "RewardValidatorTx",
  RemoveSubnetValidatorTx: "RemoveSubnetValidatorTx",
  TransformSubnetTx: "TransformSubnetTx",
  AddPermissionlessValidatorTx: "AddPermissionlessValidatorTx",
  AddPermissionlessDelegatorTx: "AddPermissionlessDelegatorTx",
  BaseTx: "BaseTx",
  TransferSubnetOwnershipTx: "TransferSubnetOwnershipTx",
  Unknown: "UNKNOWN",
} as const;
export type PChainTransactionType = ClosedEnum<typeof PChainTransactionType>;

/** @internal */
export const PChainTransactionType$inboundSchema: z.ZodNativeEnum<
  typeof PChainTransactionType
> = z.nativeEnum(PChainTransactionType);

/** @internal */
export const PChainTransactionType$outboundSchema: z.ZodNativeEnum<
  typeof PChainTransactionType
> = PChainTransactionType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PChainTransactionType$ {
  /** @deprecated use `PChainTransactionType$inboundSchema` instead. */
  export const inboundSchema = PChainTransactionType$inboundSchema;
  /** @deprecated use `PChainTransactionType$outboundSchema` instead. */
  export const outboundSchema = PChainTransactionType$outboundSchema;
}
