/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    AggregatedAssetAmount,
    AggregatedAssetAmount$inboundSchema,
    AggregatedAssetAmount$Outbound,
    AggregatedAssetAmount$outboundSchema,
} from "./aggregatedassetamount.js";
import {
    PChainSharedAsset,
    PChainSharedAsset$inboundSchema,
    PChainSharedAsset$Outbound,
    PChainSharedAsset$outboundSchema,
} from "./pchainsharedasset.js";
import * as z from "zod";

export type PChainBalance = {
    /**
     * A list of objects containing P-chain Asset basic info, amount,  and utxo count of that Asset ID.  Denotes the amount of unstaked Avax that is consumable by any transaction.
     */
    unlockedUnstaked: Array<AggregatedAssetAmount>;
    /**
     * A list of objects containing P-chain Asset basic info, amount,  and utxo count of that Asset ID.  Denotes the amount of staked Avax that is consumable by any transaction when the staking period ends.
     */
    unlockedStaked: Array<AggregatedAssetAmount>;
    /**
     * A list of objects containing P-chain Asset basic info, amount,  and utxo count of that Asset ID.  Denotes the amount of unstaked Avax that is locked at the platform level and not consumable by any transaction at the current time.
     */
    lockedPlatform: Array<AggregatedAssetAmount>;
    /**
     * A list of objects containing P-chain Asset basic info, amount,  and utxo count of that Asset ID.  Denotes the amount of unstaked Avax that is locked at the platform level and only consumeable for staking transactions.
     */
    lockedStakeable: Array<AggregatedAssetAmount>;
    /**
     * A list of objects containing P-chain Asset basic info, amount,  and utxo count of that Asset ID.  Denotes the amount of staked Avax that will be locked when the staking period ends.
     */
    lockedStaked: Array<AggregatedAssetAmount>;
    /**
     * A list of objects containing P-chain Asset basic info, amount,  and utxo count of that Asset ID.  Denotes the amount of staked Avax whose staking period has not yet started.
     */
    pendingStaked: Array<AggregatedAssetAmount>;
    /**
     * A list of objects containing P-chain Asset basic info, amount and utxo count of that Asset ID. Denotes the amount of unlocked Avax in the atomic memory between P-Chain and other chain.
     */
    atomicMemoryUnlocked: Array<PChainSharedAsset>;
    /**
     * A list of objects containing P-chain Asset basic info, amount and utxo count of that Asset ID. Denotes the amount of locked Avax in the atomic memory between P-Chain and other chain.
     */
    atomicMemoryLocked: Array<PChainSharedAsset>;
};

/** @internal */
export const PChainBalance$inboundSchema: z.ZodType<PChainBalance, z.ZodTypeDef, unknown> =
    z.object({
        unlockedUnstaked: z.array(AggregatedAssetAmount$inboundSchema),
        unlockedStaked: z.array(AggregatedAssetAmount$inboundSchema),
        lockedPlatform: z.array(AggregatedAssetAmount$inboundSchema),
        lockedStakeable: z.array(AggregatedAssetAmount$inboundSchema),
        lockedStaked: z.array(AggregatedAssetAmount$inboundSchema),
        pendingStaked: z.array(AggregatedAssetAmount$inboundSchema),
        atomicMemoryUnlocked: z.array(PChainSharedAsset$inboundSchema),
        atomicMemoryLocked: z.array(PChainSharedAsset$inboundSchema),
    });

/** @internal */
export type PChainBalance$Outbound = {
    unlockedUnstaked: Array<AggregatedAssetAmount$Outbound>;
    unlockedStaked: Array<AggregatedAssetAmount$Outbound>;
    lockedPlatform: Array<AggregatedAssetAmount$Outbound>;
    lockedStakeable: Array<AggregatedAssetAmount$Outbound>;
    lockedStaked: Array<AggregatedAssetAmount$Outbound>;
    pendingStaked: Array<AggregatedAssetAmount$Outbound>;
    atomicMemoryUnlocked: Array<PChainSharedAsset$Outbound>;
    atomicMemoryLocked: Array<PChainSharedAsset$Outbound>;
};

/** @internal */
export const PChainBalance$outboundSchema: z.ZodType<
    PChainBalance$Outbound,
    z.ZodTypeDef,
    PChainBalance
> = z.object({
    unlockedUnstaked: z.array(AggregatedAssetAmount$outboundSchema),
    unlockedStaked: z.array(AggregatedAssetAmount$outboundSchema),
    lockedPlatform: z.array(AggregatedAssetAmount$outboundSchema),
    lockedStakeable: z.array(AggregatedAssetAmount$outboundSchema),
    lockedStaked: z.array(AggregatedAssetAmount$outboundSchema),
    pendingStaked: z.array(AggregatedAssetAmount$outboundSchema),
    atomicMemoryUnlocked: z.array(PChainSharedAsset$outboundSchema),
    atomicMemoryLocked: z.array(PChainSharedAsset$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PChainBalance$ {
    /** @deprecated use `PChainBalance$inboundSchema` instead. */
    export const inboundSchema = PChainBalance$inboundSchema;
    /** @deprecated use `PChainBalance$outboundSchema` instead. */
    export const outboundSchema = PChainBalance$outboundSchema;
    /** @deprecated use `PChainBalance$Outbound` instead. */
    export type Outbound = PChainBalance$Outbound;
}
