/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Array of address activity sub-event types
 */
export const PlatformAddressActivitySubEventType = {
  BalanceChangePlatform: "balance_change_platform",
  BalanceThresholdPlatform: "balance_threshold_platform",
  RewardDistribution: "reward_distribution",
} as const;
/**
 * Array of address activity sub-event types
 */
export type PlatformAddressActivitySubEventType = ClosedEnum<
  typeof PlatformAddressActivitySubEventType
>;

/** @internal */
export const PlatformAddressActivitySubEventType$inboundSchema: z.ZodNativeEnum<
  typeof PlatformAddressActivitySubEventType
> = z.nativeEnum(PlatformAddressActivitySubEventType);

/** @internal */
export const PlatformAddressActivitySubEventType$outboundSchema:
  z.ZodNativeEnum<typeof PlatformAddressActivitySubEventType> =
    PlatformAddressActivitySubEventType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PlatformAddressActivitySubEventType$ {
  /** @deprecated use `PlatformAddressActivitySubEventType$inboundSchema` instead. */
  export const inboundSchema =
    PlatformAddressActivitySubEventType$inboundSchema;
  /** @deprecated use `PlatformAddressActivitySubEventType$outboundSchema` instead. */
  export const outboundSchema =
    PlatformAddressActivitySubEventType$outboundSchema;
}
