/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The type of key to monitor for the address activity event type.
 */
export const PlatformAddressActivityKeyType = {
  Addresses: "addresses",
} as const;
/**
 * The type of key to monitor for the address activity event type.
 */
export type PlatformAddressActivityKeyType = ClosedEnum<
  typeof PlatformAddressActivityKeyType
>;

/** @internal */
export const PlatformAddressActivityKeyType$inboundSchema: z.ZodNativeEnum<
  typeof PlatformAddressActivityKeyType
> = z.nativeEnum(PlatformAddressActivityKeyType);

/** @internal */
export const PlatformAddressActivityKeyType$outboundSchema: z.ZodNativeEnum<
  typeof PlatformAddressActivityKeyType
> = PlatformAddressActivityKeyType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PlatformAddressActivityKeyType$ {
  /** @deprecated use `PlatformAddressActivityKeyType$inboundSchema` instead. */
  export const inboundSchema = PlatformAddressActivityKeyType$inboundSchema;
  /** @deprecated use `PlatformAddressActivityKeyType$outboundSchema` instead. */
  export const outboundSchema = PlatformAddressActivityKeyType$outboundSchema;
}
