/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    ResourceLinkType,
    ResourceLinkType$inboundSchema,
    ResourceLinkType$outboundSchema,
} from "./resourcelinktype.js";
import * as z from "zod";

export type ResourceLink = {
    type: ResourceLinkType;
    url: string;
};

/** @internal */
export const ResourceLink$inboundSchema: z.ZodType<ResourceLink, z.ZodTypeDef, unknown> = z.object({
    type: ResourceLinkType$inboundSchema,
    url: z.string(),
});

/** @internal */
export type ResourceLink$Outbound = {
    type: string;
    url: string;
};

/** @internal */
export const ResourceLink$outboundSchema: z.ZodType<
    ResourceLink$Outbound,
    z.ZodTypeDef,
    ResourceLink
> = z.object({
    type: ResourceLinkType$outboundSchema,
    url: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResourceLink$ {
    /** @deprecated use `ResourceLink$inboundSchema` instead. */
    export const inboundSchema = ResourceLink$inboundSchema;
    /** @deprecated use `ResourceLink$outboundSchema` instead. */
    export const outboundSchema = ResourceLink$outboundSchema;
    /** @deprecated use `ResourceLink$Outbound` instead. */
    export type Outbound = ResourceLink$Outbound;
}
