/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SignatureAggregationResponse = {
  signedMessage: string;
};

/** @internal */
export const SignatureAggregationResponse$inboundSchema: z.ZodType<
  SignatureAggregationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  signedMessage: z.string(),
});

/** @internal */
export type SignatureAggregationResponse$Outbound = {
  signedMessage: string;
};

/** @internal */
export const SignatureAggregationResponse$outboundSchema: z.ZodType<
  SignatureAggregationResponse$Outbound,
  z.ZodTypeDef,
  SignatureAggregationResponse
> = z.object({
  signedMessage: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SignatureAggregationResponse$ {
  /** @deprecated use `SignatureAggregationResponse$inboundSchema` instead. */
  export const inboundSchema = SignatureAggregationResponse$inboundSchema;
  /** @deprecated use `SignatureAggregationResponse$outboundSchema` instead. */
  export const outboundSchema = SignatureAggregationResponse$outboundSchema;
  /** @deprecated use `SignatureAggregationResponse$Outbound` instead. */
  export type Outbound = SignatureAggregationResponse$Outbound;
}

export function signatureAggregationResponseToJSON(
  signatureAggregationResponse: SignatureAggregationResponse,
): string {
  return JSON.stringify(
    SignatureAggregationResponse$outboundSchema.parse(
      signatureAggregationResponse,
    ),
  );
}

export function signatureAggregationResponseFromJSON(
  jsonString: string,
): SafeParseResult<SignatureAggregationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SignatureAggregationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SignatureAggregationResponse' from JSON`,
  );
}
