/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    SubnetInformation,
    SubnetInformation$inboundSchema,
    SubnetInformation$Outbound,
    SubnetInformation$outboundSchema,
} from "./subnetinformation.js";
import * as z from "zod";

export type SubnetsResponse = {
    nextPageStartKey?: string | undefined;
    lastRun?: number | undefined;
    status: number;
    results: Array<SubnetInformation>;
};

/** @internal */
export const SubnetsResponse$inboundSchema: z.ZodType<SubnetsResponse, z.ZodTypeDef, unknown> =
    z.object({
        nextPageStartKey: z.string().optional(),
        lastRun: z.number().optional(),
        status: z.number(),
        results: z.array(SubnetInformation$inboundSchema),
    });

/** @internal */
export type SubnetsResponse$Outbound = {
    nextPageStartKey?: string | undefined;
    lastRun?: number | undefined;
    status: number;
    results: Array<SubnetInformation$Outbound>;
};

/** @internal */
export const SubnetsResponse$outboundSchema: z.ZodType<
    SubnetsResponse$Outbound,
    z.ZodTypeDef,
    SubnetsResponse
> = z.object({
    nextPageStartKey: z.string().optional(),
    lastRun: z.number().optional(),
    status: z.number(),
    results: z.array(SubnetInformation$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SubnetsResponse$ {
    /** @deprecated use `SubnetsResponse$inboundSchema` instead. */
    export const inboundSchema = SubnetsResponse$inboundSchema;
    /** @deprecated use `SubnetsResponse$outboundSchema` instead. */
    export const outboundSchema = SubnetsResponse$outboundSchema;
    /** @deprecated use `SubnetsResponse$Outbound` instead. */
    export type Outbound = SubnetsResponse$Outbound;
}
