/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const TransactionDirectionType = {
  SourceTransaction: "SOURCE_TRANSACTION",
  DestinationTransaction: "DESTINATION_TRANSACTION",
} as const;
export type TransactionDirectionType = ClosedEnum<
  typeof TransactionDirectionType
>;

/** @internal */
export const TransactionDirectionType$inboundSchema: z.ZodNativeEnum<
  typeof TransactionDirectionType
> = z.nativeEnum(TransactionDirectionType);

/** @internal */
export const TransactionDirectionType$outboundSchema: z.ZodNativeEnum<
  typeof TransactionDirectionType
> = TransactionDirectionType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransactionDirectionType$ {
  /** @deprecated use `TransactionDirectionType$inboundSchema` instead. */
  export const inboundSchema = TransactionDirectionType$inboundSchema;
  /** @deprecated use `TransactionDirectionType$outboundSchema` instead. */
  export const outboundSchema = TransactionDirectionType$outboundSchema;
}
