/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  PrimaryNetworkAssetCap,
  PrimaryNetworkAssetCap$inboundSchema,
  PrimaryNetworkAssetCap$outboundSchema,
} from "./primarynetworkassetcap.js";
import {
  PrimaryNetworkAssetType,
  PrimaryNetworkAssetType$inboundSchema,
  PrimaryNetworkAssetType$outboundSchema,
} from "./primarynetworkassettype.js";

export type XChainAssetDetails = {
  /**
   * Unique ID for an asset.
   */
  assetId: string;
  /**
   * Name of this asset.
   */
  name: string;
  /**
   * Symbol for this asset (max 4 characters).
   */
  symbol: string;
  /**
   * Denomination of this asset to represent fungibility.
   */
  denomination: number;
  /**
   * Type of asset like SECP256K1 or NFT.
   */
  type: PrimaryNetworkAssetType;
  /**
   * Timestamp in seconds this asset was created on.
   */
  createdAtTimestamp: number;
  /**
   * Cap represents if an asset is a variable or fixed cap asset.
   */
  cap: PrimaryNetworkAssetCap;
};

/** @internal */
export const XChainAssetDetails$inboundSchema: z.ZodType<
  XChainAssetDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  assetId: z.string(),
  name: z.string(),
  symbol: z.string(),
  denomination: z.number(),
  type: PrimaryNetworkAssetType$inboundSchema,
  createdAtTimestamp: z.number(),
  cap: PrimaryNetworkAssetCap$inboundSchema,
});

/** @internal */
export type XChainAssetDetails$Outbound = {
  assetId: string;
  name: string;
  symbol: string;
  denomination: number;
  type: string;
  createdAtTimestamp: number;
  cap: string;
};

/** @internal */
export const XChainAssetDetails$outboundSchema: z.ZodType<
  XChainAssetDetails$Outbound,
  z.ZodTypeDef,
  XChainAssetDetails
> = z.object({
  assetId: z.string(),
  name: z.string(),
  symbol: z.string(),
  denomination: z.number(),
  type: PrimaryNetworkAssetType$outboundSchema,
  createdAtTimestamp: z.number(),
  cap: PrimaryNetworkAssetCap$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace XChainAssetDetails$ {
  /** @deprecated use `XChainAssetDetails$inboundSchema` instead. */
  export const inboundSchema = XChainAssetDetails$inboundSchema;
  /** @deprecated use `XChainAssetDetails$outboundSchema` instead. */
  export const outboundSchema = XChainAssetDetails$outboundSchema;
  /** @deprecated use `XChainAssetDetails$Outbound` instead. */
  export type Outbound = XChainAssetDetails$Outbound;
}
